Cleanup pre-commit hook

diff --git a/dev/git-hooks/pre-commit b/dev/git-hooks/pre-commit
--- a/dev/git-hooks/pre-commit
+++ b/dev/git-hooks/pre-commit
@@ -2,11 +2,17 @@
 
 #######################################################################################
 #
-# This script is setup for PHP 7.2 .git/hooks/pre-commit
+# This script is setup for PHP 7.1 .git/hooks/pre-commit
 # Change the PHP variable to use a specific path/or php version
 #
 #####################################################################################
-PHP='php'
+
+#-- On Windows we point to a specific version of PHP
+if [[ "msys" = "$OSTYPE" ]]; then
+    PHP='php 7.1'
+else
+    PHP='php'
+fi
 PROJECT="."
 
 ## Fix windows paths
@@ -15,13 +21,13 @@ PROJECT=${PROJECT//\\//}
 STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
 
 # Check for phpcs config
-if [ ! -f $PROJECT/phpcs.xml ] && [ ! -f $PROJECT/phpcs.xml.dist ]; then
-  echo "$PROJECT/phpcs.xml or $PROJECT/phpcs.xml.dist not found!"
+if [[ ! -f ${PROJECT}/phpcs.xml ]] && [[ ! -f ${PROJECT}/phpcs.xml.dist ]]; then
+  echo "${PROJECT}/phpcs.xml or ${PROJECT}/phpcs.xml.dist not found!"
   exit 1;
 fi
 
 # Determine if a file list is passed.
-if [ "$#" -eq 1 ]; then
+if [[ "$#" -eq 1 ]]; then
   oIFS=$IFS
   IFS='
   '
@@ -32,23 +38,23 @@ SFILES=${SFILES:-$STAGED_FILES_CMD}
 
 # Run php lint.
 echo "Checking PHP Lint..."
-for FILE in $SFILES; do
-  $PHP -l -d display_errors=0 $PROJECT/$FILE
-  if [ $? != 0 ]; then
+for FILE in ${SFILES}; do
+  ${PHP} -l -d display_errors=0 ${PROJECT}/${FILE}
+  if [[ $? != 0 ]]; then
     echo "Fix the error before commit."
     exit 1
   fi
-  FILES="$FILES $PROJECT/$FILE"
+  FILES="${FILES} ${PROJECT}/${FILE}"
 done
 
 # Run phpcs.
-if [ "$FILES" != "" ]; then
+if [[ "${FILES}" != "" ]]; then
   echo "Running Code Sniffer."
-  phpcs --encoding=utf-8 -s -n -p $FILES
-  if [ $? != 0 ]; then
+  phpcs --encoding=utf-8 -s -n -p ${FILES}
+  if [[ $? != 0 ]]; then
     echo "Fix the error before commit!"
     echo "Run"
-    echo "  phpcbf $FILES"
+    echo "  phpcbf ${FILES}"
     echo "for automatic fix or fix it manually."
     exit 1
   fi
