Run all scans/tests on every commit

diff --git a/dev/git-hooks/pre-commit b/dev/git-hooks/pre-commit
--- a/dev/git-hooks/pre-commit
+++ b/dev/git-hooks/pre-commit
@@ -7,7 +7,7 @@
 #
 # @uses Global PHP version as different projects have different requirements.
 #
-# @version 4.5.1
+# @version 5.3.0
 #
 #####################################################################################
 
@@ -29,8 +29,7 @@ PROJECT=${PROJECT//\\//}
 
 PHP_FILES=$(git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep \\.php)
 if [[ ! "$PHP_FILES" ]]; then
-	echo "${YELLOW}[pre-commit]${BLUE} No PHP Files Changed ${RESET_COLOR}"
-	exit 0
+    echo "${YELLOW}[pre-commit]${BLUE} No Lintable PHP Files Changed ${RESET_COLOR}"
 fi
 
 function exit_reset_colors() {
@@ -39,22 +38,20 @@ function exit_reset_colors() {
 }
 
 function php_unit() {
-    if [[ "$PHP_FILES" ]]; then
-        if [[ ! -f ${PROJECT}/dev/wp-unit/phpunit.xml ]] && [[ ! -f ${PROJECT}/dev/wp-unit/phpunit.xml.dist ]]; then
-            echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/dev/wp-unit/phpunit.xml or ${PROJECT}/dev/wp-unit/phpunit.xml.dist not found!"
-            exit_reset_colors
-        fi
-        echo "${YELLOW}[pre-commit]${BLUE} Running PHP Unit... ${WHITE}"
-        cd "${PROJECT}/dev/wp-unit" || exit
-        OUTPUT=$(${PHPUNIT})
-        if [[ $? != 0 ]]; then
-            echo
-            echo "${BLUE}PHP Unit Failed! Fix the error before commit!"
-            echo "${RED}$OUTPUT"
-            exit_reset_colors
-        fi
-        echo "${YELLOW}[pre-commit]${GREEN} PHP Unit Tests Passed!${WHITE}"
+    if [[ ! -f ${PROJECT}/dev/wp-unit/phpunit.xml ]] && [[ ! -f ${PROJECT}/dev/wp-unit/phpunit.xml.dist ]]; then
+        echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/dev/wp-unit/phpunit.xml or ${PROJECT}/dev/wp-unit/phpunit.xml.dist not found!"
+        exit_reset_colors
     fi
+    echo "${YELLOW}[pre-commit]${BLUE} Running PHP Unit... ${WHITE}"
+    cd "${PROJECT}/dev/wp-unit" || exit
+    OUTPUT=$(${PHPUNIT})
+    if [[ $? != 0 ]]; then
+        echo
+        echo "${BLUE}PHP Unit Failed! Fix the error before commit!"
+        echo "${RED}$OUTPUT"
+        exit_reset_colors
+    fi
+    echo "${YELLOW}[pre-commit]${GREEN} PHP Unit Tests Passed!${WHITE}"
 }
 php_unit &
 
@@ -111,17 +108,15 @@ function php_code_sniffer() {
 php_code_sniffer &
 
 function php_stan() {
-	if [[ "$PHP_FILES" ]]; then
-		echo "${YELLOW}[pre-commit]${BLUE} Running PHP Stan... ${WHITE}"
-		OUTPUT=$(${PHPSTAN} analyse --no-progress --memory-limit=2G)
-		if [[ $? != 0 ]]; then
-			echo
-			echo "${BLUE}PHP Stan Failed. Fix the error before commit."
-			echo "${RED}$OUTPUT"
-			exit_reset_colors
-		fi
-		echo "${YELLOW}[pre-commit]${GREEN} PHP Stan Passed!${WHITE}"
-	fi
+        echo "${YELLOW}[pre-commit]${BLUE} Running PHP Stan... ${WHITE}"
+        OUTPUT=$(${PHPSTAN} analyse --no-progress --memory-limit=2G)
+        if [[ $? != 0 ]]; then
+            echo
+            echo "${BLUE}PHP Stan Failed. Fix the error before commit."
+            echo "${RED}$OUTPUT"
+            exit_reset_colors
+        fi
+        echo "${YELLOW}[pre-commit]${GREEN} PHP Stan Passed!${RESET_COLOR}"
 }
 php_stan &
 
@@ -129,14 +124,14 @@ php_stan &
 # If it sent exit code 1, it failed and the result from `wait` will be false.
 FAIL=0
 for job in $(jobs -p); do
-	wait "$job" || ((FAIL += 1))
+    wait "$job" || (( FAIL+=1 ))
 done
 
 echo "${RESET_COLOR}"
 
 # If any of the background tasks failed, we exit 1
 if [[ $FAIL -ne 0 ]]; then
-	exit 1
+    exit 1
 else
-	exit 0
+    exit 0
 fi
