Reformat pre-commit to version 3.2.1 with global services
We don't specify a PHP version because different projects have different
 PHP version requirements.

If we specify for example 7.3 and run on a project with composer locked
to 8.0, the hook will fail.

diff --git a/dev/git-hooks/pre-commit b/dev/git-hooks/pre-commit
--- a/dev/git-hooks/pre-commit
+++ b/dev/git-hooks/pre-commit
@@ -5,9 +5,9 @@
 # Test our code against various unit test systems and linters and prevent commit
 # if any of them fail.
 #
-# @uses PHP 7.3
+# @uses Global PHP version as different projects have different requirements.
 #
-# @version 2.1.0
+# @version 3.2.1
 #
 #####################################################################################
 
@@ -18,26 +18,32 @@ RED="$(tput setaf 1)"
 BLUE="$(tput setaf 6)"
 RESET_COLOR="$(tput sgr0)"
 
-#-- On Mat's machines point to a specific version of PHP.
-if [[ "mat" == "$USERNAME" ]]; then
-	PHP='php 7.3'
-	PHPUNIT="phpunit" # Composer has varying PHP version requirements.
-else
-	PHP='php'
-	PHPUNIT="phpunit"
-fi
+## Different project have different PHP version requirements.
+PHP='php'
+PHPCS='phpcs'
+PHPSTAN='phpstan'
+PHPUNIT='phpunit'
+
 PROJECT=$(${PHP} -r "echo dirname(realpath('$0'), 3);")
 ## Fix windows paths
 PROJECT=${PROJECT//\\//}
 
+JS_FILES=$(git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep "\.js$\|\.jsx$\|\.ts$\|\.tsx$")
 PHP_FILES=$(git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep \\.php)
+if [[ ! "$PHP_FILES" ]] && [[ ! "$JS_FILES" ]]; then
+    echo "${YELLOW}[pre-commit]${BLUE} No Testable Files Changed ${RESET_COLOR}"
+    exit 0
+fi
 if [[ ! "$PHP_FILES" ]]; then
-	echo "${YELLOW}[pre-commit]${BLUE} No PHP Files Changed ${WHITE}"
+    echo "${YELLOW}[pre-commit]${BLUE} No PHP Files Changed ${WHITE}"
+fi
+if [[ ! "$JS_FILES" ]]; then
+    echo "${YELLOW}[pre-commit]${BLUE} No JS Files Changed ${WHITE}"
 fi
 
 function exit_reset_colors() {
-	echo ${RESET_COLOR}
-	exit 1
+    echo ${RESET_COLOR}
+    exit 1
 }
 
 function php_unit() {
@@ -61,79 +67,100 @@ function php_unit() {
 php_unit &
 
 function php_lint() {
-	if [[ "$PHP_FILES" ]]; then
-		# Run php lint.
-		echo "${YELLOW}[pre-commit]${BLUE} Checking PHP Lint... ${WHITE}"
-		for FILE in ${PHP_FILES}; do
-			OUTPUT=$(${PHP} -l -d display_errors=0 ${PROJECT}/${FILE})
-			if [[ $? != 0 ]]; then
-				echo
-				echo "${BLUE}PHP Lint Failed. Fix the error before commit."
-				echo "${RED}$OUTPUT"
-				exit_reset_colors
-			fi
-		done
-		echo "${YELLOW}[pre-commit]${GREEN} PHP Lint Passed!${WHITE}"
-	fi
+    if [[ "$PHP_FILES" ]]; then
+        # Run php lint.
+        echo "${YELLOW}[pre-commit]${BLUE} Checking PHP Lint... ${WHITE}"
+        for FILE in ${PHP_FILES}; do
+            OUTPUT=$(${PHP} -l -d display_errors=0 ${PROJECT}/${FILE})
+            if [[ $? != 0 ]]; then
+                echo
+                echo "${BLUE}PHP Lint Failed. Fix the error before commit."
+                echo "${RED}$OUTPUT"
+                exit_reset_colors
+            fi
+        done
+        echo "${YELLOW}[pre-commit]${GREEN} PHP Lint Passed!${WHITE}"
+    fi
 }
 php_lint &
 
 function php_code_sniffer() {
-	if [[ "$PHP_FILES" != "" ]]; then
-		# Check for phpcs config
-		if [[ ! -f ${PROJECT}/phpcs.xml ]] && [[ ! -f ${PROJECT}/phpcs.xml.dist ]]; then
-			echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/phpcs.xml or ${PROJECT}/phpcs.xml.dist not found!"
-			exit_reset_colors
-		fi
-		for FILE in ${PHP_FILES}; do
-			FILES="$FILES ${PROJECT}/${FILE}"
-		done
-		echo "${YELLOW}[pre-commit]${BLUE} Running PHPCS... ${WHITE}"
-		OUTPUT=$(phpcs --encoding=utf-8 -s -n -p ${FILES})
-		if [[ $? != 0 ]]; then
-			echo
-			echo "${BLUE}PHPCS failed. Fix the error before commit!"
-			echo "${RED}$OUTPUT"
-			echo
-			echo "${YELLOW}For automatic fixes run"
-			echo
-			echo "${WHITE}phpcbf $FILES"
-			echo
-			exit_reset_colors
-		fi
-		echo "${YELLOW}[pre-commit]${GREEN} PHPCS Passed!${WHITE}"
-	fi
+    if [[ "$PHP_FILES" != "" ]]; then
+        # Check for phpcs config
+        if [[ ! -f ${PROJECT}/phpcs.xml ]] && [[ ! -f ${PROJECT}/phpcs.xml.dist ]]; then
+            echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/phpcs.xml or ${PROJECT}/phpcs.xml.dist not found!"
+            exit_reset_colors
+        fi
+        for FILE in ${PHP_FILES}; do
+            FILES="$FILES ${PROJECT}/${FILE}"
+        done
+        echo "${YELLOW}[pre-commit]${BLUE} Running PHPCS... ${WHITE}"
+        OUTPUT=$(${PHPCS} --encoding=utf-8 -s -n -p ${FILES})
+        if [[ $? != 0 ]]; then
+            echo
+            echo "${BLUE}PHPCS failed. Fix the error before commit!"
+            echo "${RED}$OUTPUT"
+            echo
+            echo "${YELLOW}For automatic fixes run"
+            echo
+            echo "${WHITE}phpcbf $FILES"
+            echo
+            exit_reset_colors
+        fi
+        echo "${YELLOW}[pre-commit]${GREEN} PHPCS Passed!${WHITE}"
+    fi
 }
 php_code_sniffer &
 
 function php_stan() {
-	if [[ "$PHP_FILES" ]]; then
-		# Run phpstan.
-		echo "${YELLOW}[pre-commit]${BLUE} Running PHP Stan... ${WHITE}"
-		OUTPUT=$(phpstan analyse --memory-limit=2G)
-		if [[ $? != 0 ]]; then
-			echo
-			echo "${BLUE}PHP Stan Failed. Fix the error before commit."
-			echo "${RED}$OUTPUT"
-			exit_reset_colors
-		fi
-		echo "${YELLOW}[pre-commit]${GREEN} PHP Stan Passed!${WHITE}"
-	fi
+    if [[ "$PHP_FILES" ]]; then
+        # Run phpstan.
+        echo "${YELLOW}[pre-commit]${BLUE} Running PHP Stan... ${WHITE}"
+        OUTPUT=$(${PHPSTAN} analyse --memory-limit=2G)
+        if [[ $? != 0 ]]; then
+            echo
+            echo "${BLUE}PHP Stan Failed. Fix the error before commit."
+            echo "${RED}$OUTPUT"
+            exit_reset_colors
+        fi
+        echo "${YELLOW}[pre-commit]${GREEN} PHP Stan Passed!${WHITE}"
+    fi
 }
 php_stan &
+
+function js_tests() {
+    # Run JS tests
+    if [[ "$JS_FILES" ]]; then
+        if [[ ! -f ${PROJECT}/wp-content/themes/core/js/jest.config.js ]]; then
+            echo "${YELLOW}[pre-commit]${BLUE} Skipping JS tests (non-existent)."
+            return
+        fi
+        echo "${YELLOW}[pre-commit]${BLUE} Running JS Tests... ${WHITE}"
+        cd "${PROJECT}/wp-content/themes/core" || exit
+        OUTPUT=$(yarn run test --bail --passWithNoTests --findRelatedTests "${JS_FILES//wp-content\/themes\/core\/js\//}" 2>&1)
+        if [[ $? != 0 ]]; then
+            echo
+            echo "${BLUE}JS Tests failed. Fix the error before commit!"
+            echo "${RED}$OUTPUT"
+            exit_reset_colors
+        fi
+        echo "${YELLOW}[pre-commit]${GREEN} JS Tests Passed!${WHITE}"
+    fi
+}
+js_tests &
 
 # Go through each background task
 # If it sent exit code 1, it failed and the result from `wait` will be false.
 FAIL=0
 for job in $(jobs -p); do
-	wait $job || let "FAIL+=1"
+    wait "$job" || (( FAIL+=1 ))
 done
 
-echo ${RESET_COLOR}
+echo "${RESET_COLOR}"
 
 # If any of the background tasks failed, we exit 1
 if [[ $FAIL -ne 0 ]]; then
-	exit 1
+    exit 1
 else
-	exit 0
+    exit 0
 fi
